"""add signups table

Revision ID: 2624e756579b
Revises: 50d1107074b3
Create Date: 2024-04-09 13:49:56.152995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2624e756579b'
down_revision = '50d1107074b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_signups_activity_id_activities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signups_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signups'))
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('registration_link')

    op.drop_table('signups')
    # ### end Alembic commands ###
