"""update date to start_time

Revision ID: 4bd88a7ce915
Revises: d71c8c3399f0
Create Date: 2024-04-10 12:09:09.396004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd88a7ce915'
down_revision = 'd71c8c3399f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'date', new_column_name='start_time' )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'start_time', new_column_name='date')
    
    # ### end Alembic commands ###
