"""add categories and activity_categories tables

Revision ID: 50d1107074b3
Revises: 4d496ff45a9b
Create Date: 2024-04-09 12:24:22.435771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d1107074b3'
down_revision = '4d496ff45a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('activity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_categories_activity_id_activities')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_activity_categories_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_categories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
