"""add reviews table

Revision ID: bacac21c6921
Revises: 4bd88a7ce915
Create Date: 2024-04-10 13:13:45.709031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacac21c6921'
down_revision = '4bd88a7ce915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_reviews_activity_id_activities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.drop_table('_alembic_tmp_activities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('street_one', sa.VARCHAR(), nullable=False),
    sa.Column('street_two', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('free', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('registration_link', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_activities')
    )
    op.drop_table('reviews')
    # ### end Alembic commands ###
